### ISSUE TITLE
Emacs 28 error

### ISSUE THREAD

**Issue by seanfarley** [alezost/org-ref-prettify.el#2] opened 2021-10-27 20:37 UTC
I seem to be getting this error when `(require 'org-ref-prettify)`:

```
Debugger entered--Lisp error: (error "Bad rx operator ‘\"cite\"’")
  error("Bad rx operator `%S'" "cite")
  rx--translate-form(("cite" "basic citation"))
  rx--translate(("cite" "basic citation"))
  rx--translate-or((("cite" "basic citation") ("nocite" "add key to bibliography, but do not cite it in the...") ("citet" "textual, Jones et al. (1990") ("citet*" "textual, full author list Jones, Baker, and Willia...") ("citep" "parenthetical citation (Jones et al. (1990)") ("citep*" "parenthetical, full author list, (Jones, Baker, an...") ("citealt" "same as citet, but without parentheses") ("citealt*" "same as citet, with full author list but without p...") ("citealp" "same as citep, but without parentheses") ("citealp*" "same as citep, with full author list, but without ...") ("citenum" "The number of the citation in the bibliography, e....") ("citetext" "text inserted in citation in the document") ("citeauthor" "Only the author, Jones et al.") ("citeauthor*" "The full author list, Jones, Baker, and Williams") ("citeyear" "The year of the citation, 2021") ("citeyearpar" "The year in parentheses (2021)") ("Citet" "like citet, but with forced capitalization for sta...") ("Citep" "like citep, but with forced capitalization for sta...") ("Citealt" "like citet, but with forced capitalization and no ...") ("Citealp" "like citep, but with forced capitalization and no ...") ("Citeauthor" "like citeauthor with forced capitalization") ("Citet*" "like citet, with full author list and forced capit...") ("Citep*" "like citep, with full author list and forced capit...") ("Citealt*" "like citet, with full author list, forced capitali...") ("Citealp*" "like citep, with full author list, forced capitali...") ("Citeauthor*" "like citeauthor with forced capitalization") ("Cite" "basic citation with capitalization") ("parencite" "similar to cite with parentheses") ("Parencite" "similar to cite with parentheses and capitalizatio...") ("footcite" "Put the citation in a footnote") ("footcitetext" "Put the citation in a footnote using \footnotetext") ("textcite" "print the authors or editors as a subject of the s...") ("Textcite" "print the authors or editors as a subject of the s...") ("smartcite" "like parencite in a footnote, and footcite in the ...") ("Smartcite" "like parencite in a footnote, and footcite in the ...") ("cite*" "similar to cite, but prints the year or title") ("parencite*" "similar to parencite, but prints the year or title") ("supercite" "superscripted numeric citation (only in numberic s...") ("autocite" "handles some punctuation nuances") ("Autocite" "handles some punctuation nuances with punctuation") ("autocite*" "same as autocite but * is passed to the backend") ("Autocite*" "same as Autocite but * is passed to the backend") ("citetitle" "the shorttitle or title field") ("citetitle*" "the full title") ("citeyear" "the year field") ("citeyear*" "the year field and extradate information if availa...") ("citedate" "the full date or year") ("citedate*" "the full date or year, including extradate informa...") ("citeurl" "the url field") ("fullcite" "create a full citation similar to what is in the b...") ...))
  rx--translate-form((or ("cite" "basic citation") ("nocite" "add key to bibliography, but do not cite it in the...") ("citet" "textual, Jones et al. (1990") ("citet*" "textual, full author list Jones, Baker, and Willia...") ("citep" "parenthetical citation (Jones et al. (1990)") ("citep*" "parenthetical, full author list, (Jones, Baker, an...") ("citealt" "same as citet, but without parentheses") ("citealt*" "same as citet, with full author list but without p...") ("citealp" "same as citep, but without parentheses") ("citealp*" "same as citep, with full author list, but without ...") ("citenum" "The number of the citation in the bibliography, e....") ("citetext" "text inserted in citation in the document") ("citeauthor" "Only the author, Jones et al.") ("citeauthor*" "The full author list, Jones, Baker, and Williams") ("citeyear" "The year of the citation, 2021") ("citeyearpar" "The year in parentheses (2021)") ("Citet" "like citet, but with forced capitalization for sta...") ("Citep" "like citep, but with forced capitalization for sta...") ("Citealt" "like citet, but with forced capitalization and no ...") ("Citealp" "like citep, but with forced capitalization and no ...") ("Citeauthor" "like citeauthor with forced capitalization") ("Citet*" "like citet, with full author list and forced capit...") ("Citep*" "like citep, with full author list and forced capit...") ("Citealt*" "like citet, with full author list, forced capitali...") ("Citealp*" "like citep, with full author list, forced capitali...") ("Citeauthor*" "like citeauthor with forced capitalization") ("Cite" "basic citation with capitalization") ("parencite" "similar to cite with parentheses") ("Parencite" "similar to cite with parentheses and capitalizatio...") ("footcite" "Put the citation in a footnote") ("footcitetext" "Put the citation in a footnote using \footnotetext") ("textcite" "print the authors or editors as a subject of the s...") ("Textcite" "print the authors or editors as a subject of the s...") ("smartcite" "like parencite in a footnote, and footcite in the ...") ("Smartcite" "like parencite in a footnote, and footcite in the ...") ("cite*" "similar to cite, but prints the year or title") ("parencite*" "similar to parencite, but prints the year or title") ("supercite" "superscripted numeric citation (only in numberic s...") ("autocite" "handles some punctuation nuances") ("Autocite" "handles some punctuation nuances with punctuation") ("autocite*" "same as autocite but * is passed to the backend") ("Autocite*" "same as Autocite but * is passed to the backend") ("citetitle" "the shorttitle or title field") ("citetitle*" "the full title") ("citeyear" "the year field") ("citeyear*" "the year field and extradate information if availa...") ("citedate" "the full date or year") ("citedate*" "the full date or year, including extradate informa...") ("citeurl" "the url field") ...))
  rx--translate((or ("cite" "basic citation") ("nocite" "add key to bibliography, but do not cite it in the...") ("citet" "textual, Jones et al. (1990") ("citet*" "textual, full author list Jones, Baker, and Willia...") ("citep" "parenthetical citation (Jones et al. (1990)") ("citep*" "parenthetical, full author list, (Jones, Baker, an...") ("citealt" "same as citet, but without parentheses") ("citealt*" "same as citet, with full author list but without p...") ("citealp" "same as citep, but without parentheses") ("citealp*" "same as citep, with full author list, but without ...") ("citenum" "The number of the citation in the bibliography, e....") ("citetext" "text inserted in citation in the document") ("citeauthor" "Only the author, Jones et al.") ("citeauthor*" "The full author list, Jones, Baker, and Williams") ("citeyear" "The year of the citation, 2021") ("citeyearpar" "The year in parentheses (2021)") ("Citet" "like citet, but with forced capitalization for sta...") ("Citep" "like citep, but with forced capitalization for sta...") ("Citealt" "like citet, but with forced capitalization and no ...") ("Citealp" "like citep, but with forced capitalization and no ...") ("Citeauthor" "like citeauthor with forced capitalization") ("Citet*" "like citet, with full author list and forced capit...") ("Citep*" "like citep, with full author list and forced capit...") ("Citealt*" "like citet, with full author list, forced capitali...") ("Citealp*" "like citep, with full author list, forced capitali...") ("Citeauthor*" "like citeauthor with forced capitalization") ("Cite" "basic citation with capitalization") ("parencite" "similar to cite with parentheses") ("Parencite" "similar to cite with parentheses and capitalizatio...") ("footcite" "Put the citation in a footnote") ("footcitetext" "Put the citation in a footnote using \footnotetext") ("textcite" "print the authors or editors as a subject of the s...") ("Textcite" "print the authors or editors as a subject of the s...") ("smartcite" "like parencite in a footnote, and footcite in the ...") ("Smartcite" "like parencite in a footnote, and footcite in the ...") ("cite*" "similar to cite, but prints the year or title") ("parencite*" "similar to parencite, but prints the year or title") ("supercite" "superscripted numeric citation (only in numberic s...") ("autocite" "handles some punctuation nuances") ("Autocite" "handles some punctuation nuances with punctuation") ("autocite*" "same as autocite but * is passed to the backend") ("Autocite*" "same as Autocite but * is passed to the backend") ("citetitle" "the shorttitle or title field") ("citetitle*" "the full title") ("citeyear" "the year field") ("citeyear*" "the year field and extradate information if availa...") ("citedate" "the full date or year") ("citedate*" "the full date or year, including extradate informa...") ("citeurl" "the url field") ...))
  rx--translate-seq(((or ("cite" "basic citation") ("nocite" "add key to bibliography, but do not cite it in the...") ("citet" "textual, Jones et al. (1990") ("citet*" "textual, full author list Jones, Baker, and Willia...") ("citep" "parenthetical citation (Jones et al. (1990)") ("citep*" "parenthetical, full author list, (Jones, Baker, an...") ("citealt" "same as citet, but without parentheses") ("citealt*" "same as citet, with full author list but without p...") ("citealp" "same as citep, but without parentheses") ("citealp*" "same as citep, with full author list, but without ...") ("citenum" "The number of the citation in the bibliography, e....") ("citetext" "text inserted in citation in the document") ("citeauthor" "Only the author, Jones et al.") ("citeauthor*" "The full author list, Jones, Baker, and Williams") ("citeyear" "The year of the citation, 2021") ("citeyearpar" "The year in parentheses (2021)") ("Citet" "like citet, but with forced capitalization for sta...") ("Citep" "like citep, but with forced capitalization for sta...") ("Citealt" "like citet, but with forced capitalization and no ...") ("Citealp" "like citep, but with forced capitalization and no ...") ("Citeauthor" "like citeauthor with forced capitalization") ("Citet*" "like citet, with full author list and forced capit...") ("Citep*" "like citep, with full author list and forced capit...") ("Citealt*" "like citet, with full author list, forced capitali...") ("Citealp*" "like citep, with full author list, forced capitali...") ("Citeauthor*" "like citeauthor with forced capitalization") ("Cite" "basic citation with capitalization") ("parencite" "similar to cite with parentheses") ("Parencite" "similar to cite with parentheses and capitalizatio...") ("footcite" "Put the citation in a footnote") ("footcitetext" "Put the citation in a footnote using \footnotetext") ("textcite" "print the authors or editors as a subject of the s...") ("Textcite" "print the authors or editors as a subject of the s...") ("smartcite" "like parencite in a footnote, and footcite in the ...") ("Smartcite" "like parencite in a footnote, and footcite in the ...") ("cite*" "similar to cite, but prints the year or title") ("parencite*" "similar to parencite, but prints the year or title") ("supercite" "superscripted numeric citation (only in numberic s...") ("autocite" "handles some punctuation nuances") ("Autocite" "handles some punctuation nuances with punctuation") ("autocite*" "same as autocite but * is passed to the backend") ("Autocite*" "same as Autocite but * is passed to the backend") ("citetitle" "the shorttitle or title field") ("citetitle*" "the full title") ("citeyear" "the year field") ("citeyear*" "the year field and extradate information if availa...") ("citedate" "the full date or year") ("citedate*" "the full date or year, including extradate informa...") ("citeurl" "the url field") ...)))
  rx--translate-group(((or ("cite" "basic citation") ("nocite" "add key to bibliography, but do not cite it in the...") ("citet" "textual, Jones et al. (1990") ("citet*" "textual, full author list Jones, Baker, and Willia...") ("citep" "parenthetical citation (Jones et al. (1990)") ("citep*" "parenthetical, full author list, (Jones, Baker, an...") ("citealt" "same as citet, but without parentheses") ("citealt*" "same as citet, with full author list but without p...") ("citealp" "same as citep, but without parentheses") ("citealp*" "same as citep, with full author list, but without ...") ("citenum" "The number of the citation in the bibliography, e....") ("citetext" "text inserted in citation in the document") ("citeauthor" "Only the author, Jones et al.") ("citeauthor*" "The full author list, Jones, Baker, and Williams") ("citeyear" "The year of the citation, 2021") ("citeyearpar" "The year in parentheses (2021)") ("Citet" "like citet, but with forced capitalization for sta...") ("Citep" "like citep, but with forced capitalization for sta...") ("Citealt" "like citet, but with forced capitalization and no ...") ("Citealp" "like citep, but with forced capitalization and no ...") ("Citeauthor" "like citeauthor with forced capitalization") ("Citet*" "like citet, with full author list and forced capit...") ("Citep*" "like citep, with full author list and forced capit...") ("Citealt*" "like citet, with full author list, forced capitali...") ("Citealp*" "like citep, with full author list, forced capitali...") ("Citeauthor*" "like citeauthor with forced capitalization") ("Cite" "basic citation with capitalization") ("parencite" "similar to cite with parentheses") ("Parencite" "similar to cite with parentheses and capitalizatio...") ("footcite" "Put the citation in a footnote") ("footcitetext" "Put the citation in a footnote using \footnotetext") ("textcite" "print the authors or editors as a subject of the s...") ("Textcite" "print the authors or editors as a subject of the s...") ("smartcite" "like parencite in a footnote, and footcite in the ...") ("Smartcite" "like parencite in a footnote, and footcite in the ...") ("cite*" "similar to cite, but prints the year or title") ("parencite*" "similar to parencite, but prints the year or title") ("supercite" "superscripted numeric citation (only in numberic s...") ("autocite" "handles some punctuation nuances") ("Autocite" "handles some punctuation nuances with punctuation") ("autocite*" "same as autocite but * is passed to the backend") ("Autocite*" "same as Autocite but * is passed to the backend") ("citetitle" "the shorttitle or title field") ("citetitle*" "the full title") ("citeyear" "the year field") ("citeyear*" "the year field and extradate information if availa...") ("citedate" "the full date or year") ("citedate*" "the full date or year, including extradate informa...") ("citeurl" "the url field") ...)))
  rx--translate-form((group (or ("cite" "basic citation") ("nocite" "add key to bibliography, but do not cite it in the...") ("citet" "textual, Jones et al. (1990") ("citet*" "textual, full author list Jones, Baker, and Willia...") ("citep" "parenthetical citation (Jones et al. (1990)") ("citep*" "parenthetical, full author list, (Jones, Baker, an...") ("citealt" "same as citet, but without parentheses") ("citealt*" "same as citet, with full author list but without p...") ("citealp" "same as citep, but without parentheses") ("citealp*" "same as citep, with full author list, but without ...") ("citenum" "The number of the citation in the bibliography, e....") ("citetext" "text inserted in citation in the document") ("citeauthor" "Only the author, Jones et al.") ("citeauthor*" "The full author list, Jones, Baker, and Williams") ("citeyear" "The year of the citation, 2021") ("citeyearpar" "The year in parentheses (2021)") ("Citet" "like citet, but with forced capitalization for sta...") ("Citep" "like citep, but with forced capitalization for sta...") ("Citealt" "like citet, but with forced capitalization and no ...") ("Citealp" "like citep, but with forced capitalization and no ...") ("Citeauthor" "like citeauthor with forced capitalization") ("Citet*" "like citet, with full author list and forced capit...") ("Citep*" "like citep, with full author list and forced capit...") ("Citealt*" "like citet, with full author list, forced capitali...") ("Citealp*" "like citep, with full author list, forced capitali...") ("Citeauthor*" "like citeauthor with forced capitalization") ("Cite" "basic citation with capitalization") ("parencite" "similar to cite with parentheses") ("Parencite" "similar to cite with parentheses and capitalizatio...") ("footcite" "Put the citation in a footnote") ("footcitetext" "Put the citation in a footnote using \footnotetext") ("textcite" "print the authors or editors as a subject of the s...") ("Textcite" "print the authors or editors as a subject of the s...") ("smartcite" "like parencite in a footnote, and footcite in the ...") ("Smartcite" "like parencite in a footnote, and footcite in the ...") ("cite*" "similar to cite, but prints the year or title") ("parencite*" "similar to parencite, but prints the year or title") ("supercite" "superscripted numeric citation (only in numberic s...") ("autocite" "handles some punctuation nuances") ("Autocite" "handles some punctuation nuances with punctuation") ("autocite*" "same as autocite but * is passed to the backend") ("Autocite*" "same as Autocite but * is passed to the backend") ("citetitle" "the shorttitle or title field") ("citetitle*" "the full title") ("citeyear" "the year field") ("citeyear*" "the year field and extradate information if availa...") ("citedate" "the full date or year") ("citedate*" "the full date or year, including extradate informa...") ("citeurl" "the url field") ...)))
  rx--translate((group (or ("cite" "basic citation") ("nocite" "add key to bibliography, but do not cite it in the...") ("citet" "textual, Jones et al. (1990") ("citet*" "textual, full author list Jones, Baker, and Willia...") ("citep" "parenthetical citation (Jones et al. (1990)") ("citep*" "parenthetical, full author list, (Jones, Baker, an...") ("citealt" "same as citet, but without parentheses") ("citealt*" "same as citet, with full author list but without p...") ("citealp" "same as citep, but without parentheses") ("citealp*" "same as citep, with full author list, but without ...") ("citenum" "The number of the citation in the bibliography, e....") ("citetext" "text inserted in citation in the document") ("citeauthor" "Only the author, Jones et al.") ("citeauthor*" "The full author list, Jones, Baker, and Williams") ("citeyear" "The year of the citation, 2021") ("citeyearpar" "The year in parentheses (2021)") ("Citet" "like citet, but with forced capitalization for sta...") ("Citep" "like citep, but with forced capitalization for sta...") ("Citealt" "like citet, but with forced capitalization and no ...") ("Citealp" "like citep, but with forced capitalization and no ...") ("Citeauthor" "like citeauthor with forced capitalization") ("Citet*" "like citet, with full author list and forced capit...") ("Citep*" "like citep, with full author list and forced capit...") ("Citealt*" "like citet, with full author list, forced capitali...") ("Citealp*" "like citep, with full author list, forced capitali...") ("Citeauthor*" "like citeauthor with forced capitalization") ("Cite" "basic citation with capitalization") ("parencite" "similar to cite with parentheses") ("Parencite" "similar to cite with parentheses and capitalizatio...") ("footcite" "Put the citation in a footnote") ("footcitetext" "Put the citation in a footnote using \footnotetext") ("textcite" "print the authors or editors as a subject of the s...") ("Textcite" "print the authors or editors as a subject of the s...") ("smartcite" "like parencite in a footnote, and footcite in the ...") ("Smartcite" "like parencite in a footnote, and footcite in the ...") ("cite*" "similar to cite, but prints the year or title") ("parencite*" "similar to parencite, but prints the year or title") ("supercite" "superscripted numeric citation (only in numberic s...") ("autocite" "handles some punctuation nuances") ("Autocite" "handles some punctuation nuances with punctuation") ("autocite*" "same as autocite but * is passed to the backend") ("Autocite*" "same as Autocite but * is passed to the backend") ("citetitle" "the shorttitle or title field") ("citetitle*" "the full title") ("citeyear" "the year field") ("citeyear*" "the year field and extradate information if availa...") ("citedate" "the full date or year") ("citedate*" "the full date or year, including extradate informa...") ("citeurl" "the url field") ...)))
  rx--translate-seq(((32 "[[") (group (or ("cite" "basic citation") ("nocite" "add key to bibliography, but do not cite it in the...") ("citet" "textual, Jones et al. (1990") ("citet*" "textual, full author list Jones, Baker, and Willia...") ("citep" "parenthetical citation (Jones et al. (1990)") ("citep*" "parenthetical, full author list, (Jones, Baker, an...") ("citealt" "same as citet, but without parentheses") ("citealt*" "same as citet, with full author list but without p...") ("citealp" "same as citep, but without parentheses") ("citealp*" "same as citep, with full author list, but without ...") ("citenum" "The number of the citation in the bibliography, e....") ("citetext" "text inserted in citation in the document") ("citeauthor" "Only the author, Jones et al.") ("citeauthor*" "The full author list, Jones, Baker, and Williams") ("citeyear" "The year of the citation, 2021") ("citeyearpar" "The year in parentheses (2021)") ("Citet" "like citet, but with forced capitalization for sta...") ("Citep" "like citep, but with forced capitalization for sta...") ("Citealt" "like citet, but with forced capitalization and no ...") ("Citealp" "like citep, but with forced capitalization and no ...") ("Citeauthor" "like citeauthor with forced capitalization") ("Citet*" "like citet, with full author list and forced capit...") ("Citep*" "like citep, with full author list and forced capit...") ("Citealt*" "like citet, with full author list, forced capitali...") ("Citealp*" "like citep, with full author list, forced capitali...") ("Citeauthor*" "like citeauthor with forced capitalization") ("Cite" "basic citation with capitalization") ("parencite" "similar to cite with parentheses") ("Parencite" "similar to cite with parentheses and capitalizatio...") ("footcite" "Put the citation in a footnote") ("footcitetext" "Put the citation in a footnote using \footnotetext") ("textcite" "print the authors or editors as a subject of the s...") ("Textcite" "print the authors or editors as a subject of the s...") ("smartcite" "like parencite in a footnote, and footcite in the ...") ("Smartcite" "like parencite in a footnote, and footcite in the ...") ("cite*" "similar to cite, but prints the year or title") ("parencite*" "similar to parencite, but prints the year or title") ("supercite" "superscripted numeric citation (only in numberic s...") ("autocite" "handles some punctuation nuances") ("Autocite" "handles some punctuation nuances with punctuation") ("autocite*" "same as autocite but * is passed to the backend") ("Autocite*" "same as Autocite but * is passed to the backend") ("citetitle" "the shorttitle or title field") ("citetitle*" "the full title") ("citeyear" "the year field") ("citeyear*" "the year field and extradate information if availa...") ("citedate" "the full date or year") ("citedate*" "the full date or year, including extradate informa...") ("citeurl" "the url field") ...)) ":" (group (one-or-more (any alnum "-_,"))) (32 "]") (32 "[" (32 (group (* (any alpha space))) "::") (group (* (any digit "-"))) (32 "::" (group (* (not "]")))) "]") (32 "]")))
  rx--translate-form((and (32 "[[") (group (or ("cite" "basic citation") ("nocite" "add key to bibliography, but do not cite it in the...") ("citet" "textual, Jones et al. (1990") ("citet*" "textual, full author list Jones, Baker, and Willia...") ("citep" "parenthetical citation (Jones et al. (1990)") ("citep*" "parenthetical, full author list, (Jones, Baker, an...") ("citealt" "same as citet, but without parentheses") ("citealt*" "same as citet, with full author list but without p...") ("citealp" "same as citep, but without parentheses") ("citealp*" "same as citep, with full author list, but without ...") ("citenum" "The number of the citation in the bibliography, e....") ("citetext" "text inserted in citation in the document") ("citeauthor" "Only the author, Jones et al.") ("citeauthor*" "The full author list, Jones, Baker, and Williams") ("citeyear" "The year of the citation, 2021") ("citeyearpar" "The year in parentheses (2021)") ("Citet" "like citet, but with forced capitalization for sta...") ("Citep" "like citep, but with forced capitalization for sta...") ("Citealt" "like citet, but with forced capitalization and no ...") ("Citealp" "like citep, but with forced capitalization and no ...") ("Citeauthor" "like citeauthor with forced capitalization") ("Citet*" "like citet, with full author list and forced capit...") ("Citep*" "like citep, with full author list and forced capit...") ("Citealt*" "like citet, with full author list, forced capitali...") ("Citealp*" "like citep, with full author list, forced capitali...") ("Citeauthor*" "like citeauthor with forced capitalization") ("Cite" "basic citation with capitalization") ("parencite" "similar to cite with parentheses") ("Parencite" "similar to cite with parentheses and capitalizatio...") ("footcite" "Put the citation in a footnote") ("footcitetext" "Put the citation in a footnote using \footnotetext") ("textcite" "print the authors or editors as a subject of the s...") ("Textcite" "print the authors or editors as a subject of the s...") ("smartcite" "like parencite in a footnote, and footcite in the ...") ("Smartcite" "like parencite in a footnote, and footcite in the ...") ("cite*" "similar to cite, but prints the year or title") ("parencite*" "similar to parencite, but prints the year or title") ("supercite" "superscripted numeric citation (only in numberic s...") ("autocite" "handles some punctuation nuances") ("Autocite" "handles some punctuation nuances with punctuation") ("autocite*" "same as autocite but * is passed to the backend") ("Autocite*" "same as Autocite but * is passed to the backend") ("citetitle" "the shorttitle or title field") ("citetitle*" "the full title") ("citeyear" "the year field") ("citeyear*" "the year field and extradate information if availa...") ("citedate" "the full date or year") ("citedate*" "the full date or year, including extradate informa...") ("citeurl" "the url field") ...)) ":" (group (one-or-more (any alnum "-_,"))) (32 "]") (32 "[" (32 (group (* (any alpha space))) "::") (group (* (any digit "-"))) (32 "::" (group (* (not "]")))) "]") (32 "]")))
  rx--translate((and (32 "[[") (group (or ("cite" "basic citation") ("nocite" "add key to bibliography, but do not cite it in the...") ("citet" "textual, Jones et al. (1990") ("citet*" "textual, full author list Jones, Baker, and Willia...") ("citep" "parenthetical citation (Jones et al. (1990)") ("citep*" "parenthetical, full author list, (Jones, Baker, an...") ("citealt" "same as citet, but without parentheses") ("citealt*" "same as citet, with full author list but without p...") ("citealp" "same as citep, but without parentheses") ("citealp*" "same as citep, with full author list, but without ...") ("citenum" "The number of the citation in the bibliography, e....") ("citetext" "text inserted in citation in the document") ("citeauthor" "Only the author, Jones et al.") ("citeauthor*" "The full author list, Jones, Baker, and Williams") ("citeyear" "The year of the citation, 2021") ("citeyearpar" "The year in parentheses (2021)") ("Citet" "like citet, but with forced capitalization for sta...") ("Citep" "like citep, but with forced capitalization for sta...") ("Citealt" "like citet, but with forced capitalization and no ...") ("Citealp" "like citep, but with forced capitalization and no ...") ("Citeauthor" "like citeauthor with forced capitalization") ("Citet*" "like citet, with full author list and forced capit...") ("Citep*" "like citep, with full author list and forced capit...") ("Citealt*" "like citet, with full author list, forced capitali...") ("Citealp*" "like citep, with full author list, forced capitali...") ("Citeauthor*" "like citeauthor with forced capitalization") ("Cite" "basic citation with capitalization") ("parencite" "similar to cite with parentheses") ("Parencite" "similar to cite with parentheses and capitalizatio...") ("footcite" "Put the citation in a footnote") ("footcitetext" "Put the citation in a footnote using \footnotetext") ("textcite" "print the authors or editors as a subject of the s...") ("Textcite" "print the authors or editors as a subject of the s...") ("smartcite" "like parencite in a footnote, and footcite in the ...") ("Smartcite" "like parencite in a footnote, and footcite in the ...") ("cite*" "similar to cite, but prints the year or title") ("parencite*" "similar to parencite, but prints the year or title") ("supercite" "superscripted numeric citation (only in numberic s...") ("autocite" "handles some punctuation nuances") ("Autocite" "handles some punctuation nuances with punctuation") ("autocite*" "same as autocite but * is passed to the backend") ("Autocite*" "same as Autocite but * is passed to the backend") ("citetitle" "the shorttitle or title field") ("citetitle*" "the full title") ("citeyear" "the year field") ("citeyear*" "the year field and extradate information if availa...") ("citedate" "the full date or year") ("citedate*" "the full date or year, including extradate informa...") ("citeurl" "the url field") ...)) ":" (group (one-or-more (any alnum "-_,"))) (32 "]") (32 "[" (32 (group (* (any alpha space))) "::") (group (* (any digit "-"))) (32 "::" (group (* (not "]")))) "]") (32 "]")))
  rx-to-string((and (32 "[[") (group (or ("cite" "basic citation") ("nocite" "add key to bibliography, but do not cite it in the...") ("citet" "textual, Jones et al. (1990") ("citet*" "textual, full author list Jones, Baker, and Willia...") ("citep" "parenthetical citation (Jones et al. (1990)") ("citep*" "parenthetical, full author list, (Jones, Baker, an...") ("citealt" "same as citet, but without parentheses") ("citealt*" "same as citet, with full author list but without p...") ("citealp" "same as citep, but without parentheses") ("citealp*" "same as citep, with full author list, but without ...") ("citenum" "The number of the citation in the bibliography, e....") ("citetext" "text inserted in citation in the document") ("citeauthor" "Only the author, Jones et al.") ("citeauthor*" "The full author list, Jones, Baker, and Williams") ("citeyear" "The year of the citation, 2021") ("citeyearpar" "The year in parentheses (2021)") ("Citet" "like citet, but with forced capitalization for sta...") ("Citep" "like citep, but with forced capitalization for sta...") ("Citealt" "like citet, but with forced capitalization and no ...") ("Citealp" "like citep, but with forced capitalization and no ...") ("Citeauthor" "like citeauthor with forced capitalization") ("Citet*" "like citet, with full author list and forced capit...") ("Citep*" "like citep, with full author list and forced capit...") ("Citealt*" "like citet, with full author list, forced capitali...") ("Citealp*" "like citep, with full author list, forced capitali...") ("Citeauthor*" "like citeauthor with forced capitalization") ("Cite" "basic citation with capitalization") ("parencite" "similar to cite with parentheses") ("Parencite" "similar to cite with parentheses and capitalizatio...") ("footcite" "Put the citation in a footnote") ("footcitetext" "Put the citation in a footnote using \footnotetext") ("textcite" "print the authors or editors as a subject of the s...") ("Textcite" "print the authors or editors as a subject of the s...") ("smartcite" "like parencite in a footnote, and footcite in the ...") ("Smartcite" "like parencite in a footnote, and footcite in the ...") ("cite*" "similar to cite, but prints the year or title") ("parencite*" "similar to parencite, but prints the year or title") ("supercite" "superscripted numeric citation (only in numberic s...") ("autocite" "handles some punctuation nuances") ("Autocite" "handles some punctuation nuances with punctuation") ("autocite*" "same as autocite but * is passed to the backend") ("Autocite*" "same as Autocite but * is passed to the backend") ("citetitle" "the shorttitle or title field") ("citetitle*" "the full title") ("citeyear" "the year field") ("citeyear*" "the year field and extradate information if availa...") ("citedate" "the full date or year") ("citedate*" "the full date or year, including extradate informa...") ("citeurl" "the url field") ...)) ":" (group (one-or-more (any alnum "-_,"))) (32 "]") (32 "[" (32 (group (* (any alpha space))) "::") (group (* (any digit "-"))) (32 "::" (group (* (not "]")))) "]") (32 "]")) t)
  byte-code("\301\302\303\304\305\10BD\306BBB\307\"\207" [org-ref-cite-types rx-to-string and (32 "[[") group or (":" (group (one-or-more (any alnum "-_,"))) (32 "]") (32 "[" (32 (group (* (any alpha space))) "::") (group (* (any digit "-"))) (32 "::" (group (* (not "]")))) "]") (32 "]")) t] 6)
  (defvar org-ref-prettify-regexp (byte-code "\301\302\303\304\305\10BD\306BBB\307\"\207" [org-ref-cite-types rx-to-string and (32 "[[") group or (":" (group (one-or-more (any alnum "-_,"))) (32 "]") (32 "[" (32 (group (* ...)) "::") (group (* (any digit "-"))) (32 "::" (group (* ...))) "]") (32 "]")) t] 6) "Regular expression to match a citation link.")
  require(org-ref-prettify)
  eval-expression((require 'org-ref-prettify) nil nil 127)
  funcall-interactively(eval-expression (require 'org-ref-prettify) nil nil 127)
  #<subr command-execute>(eval-expression nil nil nil)
  ad-Advice-command-execute(#<subr command-execute> eval-expression)
  apply(ad-Advice-command-execute #<subr command-execute> eval-expression)
  command-execute(eval-expression)
```

Perhaps something changed with `rx` in Emacs 28?

**Comment by alezost** [comment] 2021-11-11 07:54
Hello, Sean!
Thank you for this report, and sorry for the long delay :)

The problem is not caused by Emacs 28 but by a change in `org-ref`.
This should be fixed by the following commits:
https://github.com/jkitchin/org-ref/commit/c87b4155cd2f60ca3a9bed2e6e366c1fa47aec33
https://github.com/alezost/org-ref-prettify.el/commit/dd94cef771f1dafd00b40660e3f875a80b8d46ae

I.e., this issue should be solved with the latest `org-ref` and
`org-ref-prettify` from MELPA.  Please, let me know if there is a
problem still.

**Closed as completed by alezost** 2021-11-11 07:54 UTC

**Comment by seanfarley** [comment] 2021-11-11 19:13
Thanks so much!
